### ISSUE TITLE
Ref

### ISSUE THREAD

**Issue by Krauszie** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-masriri#16]
![Capture](https://user-images.githubusercontent.com/50489529/67748436-81e9da80-fa5d-11e9-8e1e-d4214bff0341.jpg)

itu signupnya blm d ref

**Comment by ghifariakbar01** [comment]
<img width="986" alt="Screen Shot 2019-10-29 at 21 54 31" src="https://user-images.githubusercontent.com/49737426/67779049-b2019f80-fa96-11e9-9db2-63ceb2b18886.png">

udh
